@include('layouts.app_css')
@include('layouts.app_header')
@include('layouts.app_menu')
@include('layouts.app_breadcrumbs')
@yield('content')
@include('layouts.app_footer')
@include('layouts.app_js')
